version: '3.3'
services:
  db:
    image: postgres
    container_name: postgres1
    restart: always
    networks:
      dev:
        aliases:
        - postgres.docker
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hello_World
    ports:
      - 5432:5432
  web:
    build: ./target
    depends_on:
      - db
    restart: always
    ports:
      - 8585:8585
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    networks:
      dev:
        aliases:
        - web.docker
networks:
  dev:
