
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hello_World
      ports:
        - 5432:5432
  web:
    image: app-postgres
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST = db
      - DATABASE_USER = postgres
      - DATABASE_PASSWORD = 123456
      - DATABASE_PORT = 5432
