services:

  postgres:
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: mysql
        - POSTGRES_PASSWORD=123456
        - POSTGRES_USER=postgres
        - POSTGRES_DB=hello_World
      ports:
        - 5432:5432
  app:
    image: app-postgres
    restart: always
    ports:
      - 8080:8080


