services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD = 123456
      POSTGRES_USER = postgres
      POSTGRES_DB = hello_World
    ports:
         5432:5432
    adminer:
      image: user-postgres
      restart: always
      port:
          8080-8080
